=== snehasis419/iwp_lab/internet and web prog lab/xml_snehasis(10bce1099)/railway/rail.dtd
<!ELEMENT Railways (RailwayTicket)>
<!ELEMENT RailwayTicket (source,destination,pdetails,bookeddate,amt)>
<!ELEMENT source (stationName,stationCode)>
<!ELEMENT destination (stationName,stationCode>
<!ELEMENT stationName (#PCDATA)>
<!ELEMENT stationCode (#PCDATA)>
<!ELEMENT pdetails (name,age,sex,seniorCitizen)>
<!ELEMENT name(title,actualName)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT actualName (#PCDATA)>
<!ELEMENT age(#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT seniorCitizen (#PCDATA)>
<!ELEMENT bookeddate (#PCDATA)>
<!ELEMENT amt (#PCDATA)>

=== snehasis419/iwp_lab/internet and web prog lab/xml_snehasis(10bce1099)/railway/railway.xml
<?xml version="1.0" ?>
<!DOCTYPE root-element SYSTEM "rail.dtd"> 
<Railways xmlns="" xmlns:xsi="cdef" xsi:schemaLocation="rails.xsd">
   <RailwayTicket type="A">
      <source>
	     <stationName>VAN</stationName>
		 <stationCode>123</stationCode>
       </source>
       <destination>
          <stationName>KOL</stationName>
          <stationCode>456</stationCode>
        </destination>
        <pdetails>
            <name>
                <title>Mr</title>
                <actualName>tom</actualName>
            </name>
            <age>25</age>
            <sex>male</sex>
            <seniorCitizen>no</seniorCitizen>
         </pdetails>
         <bookeddate>12-03-1992</bookeddate>
         <amt>192.00</amt>
    </RailwayTicket>
</Railways>
